### PR TITLE
Friend Feed feature + Minor changes in Request

### PR DESCRIPTION
**Pull request by liorsicd**
### friend feed feature
In our app, all friends need the option to see the founded furniture that answering their request.

for that, I build a new feature, FriendFeed, that show the data to the friend.

1. build the logic side -

- model - connected to DB
-connect the model to the admin site
- view and URL

2. build basic HTML feed to show the data (rendered by the Django view)
solve #17

replace #18 

### Minor changes in Request

After the first draft, we learned (together with @nadavshoshan) that Django can generate the HTML form from the related model.
It's also very helpful when we want to set limits options in the form (Enum).

So after the change now our request form is generated by Django and sends to the HTML file as an object.

### CODE REVIEW

**Review by ifireball — CHANGES_REQUESTED** [review]
This is a huge PR and the list of commits does not help me understand it - 300 line PR ~can~ be OK but I need to see very good commits in it that split it up to smaller understandable parts.

Here I'm seeing a lot of branch merges and other "mess" in the list of commits. Please clean up this PR.

**Comment by liorsicd** [comment]
@ifireball  In 'clean it up' you mean rebase those commits and split them to small commits?
also is it possible to remove all the branch merging from the log (without losing any file..)?

**Comment by ifireball** [comment]
Rebase commits, make sure each one deals with a single topic and has a good, descriptive, commit message, and that when read it series they "add up" to tell the full story of the PR. Don't have "junk" commits like "moved file X" or "fixed after comments".

A metaphor I sometimes use is that a PR is a presentation about a change you're making and each commit is a slide within that presentation.

About the branch merges - assuming all those branches were merged into master already - rebasing should remove them from the PR history - if they were not merged you need to submit them as PRs.

**Comment by liorsicd** [comment]
@ifireball 
`if they were not merged you need to submit them as PRs.`

I am this situation : 

image


all of those commits are merges.
so I need to create PR just for them to 'clear' it? (before I will push my new commits)

**Pull request closed without merging**
