### PR TITLE
Testing for gatherer component

### PR DESCRIPTION
**Pull request by rotem-benzvi**
now we can test the gatherer flow from friend request to founds. the commit:
1. tests.py file which include test for every part.
2. we use pytest so install it.
3. some minor changes in agora for our test

Fix: #105
Fixed: #100

### CODE REVIEW

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
1. CI is broken. The log file is full of errors.
2. Test files should be placed in a tests folder
3. Are you sure those tests are executed by CI?

**Comment by liorsicd** [comment]
> 1. CI is broken. The log file is full of errors.
> 2. Test files should be placed in a tests folder
> 3. Are you sure those tests are executed by CI?

@lioramilbaum 
about the broken CI:
1. is it the lint CI?
2. it ok to open PR with lint fixing to all pages in our application?

**Comment by lioramilbaum** [comment]
> @lioramilbaum @rotem-benzvi
> 
> > 1. CI is broken. The log file is full of errors.
> 
> 1. is it the lint CI?
maybe. go over the logs, step by step
> 2. it ok to open PR with lint fixing to all pages in our application?
It is
> 
> > 1. Are you sure those tests are executed by CI?
> 
> our CI doesn't run those tests yet
Then change that. How can I get confidence in the contributed code?

**Comment by rotem-benzvi** [comment]
ok so me and @liorsicd  look over the logs there is 2 things:
1. 1 warining that connect to apt, but its not fails so working now to fix it in different PR (CI PR).
2. warning that connected to Lint but only syntax stuff for example-
imported but unused
line too long
trailing whitespace
blank line at end of file
whitespace before ','
local variable 'context' is assigned to but never used
unexpected spaces around keyword / parameter equals
missing whitespace around operator

finally the CI passed, so its look like this specific test is fine, so we suggest that we merge this PR, and we open issues-
1. fix Lint CI 
2. fix apt
3. after nadav will merge the new test dir i will move this file to test dir.
4. most important thing - lior work that CI will run those test file.

@lioramilbaum , sound ok?

**Review by lioramilbaum — APPROVED** [review]

**Pull request merged**
