### PR TITLE
test moduls for coordinate and friendreq

### PR DESCRIPTION
**Pull request by nadavshoshan**
minor syntax change for friendreq app
add new test modul for coordinate app:
1. test urls.
2. test html pages rendering.
3. test post/ get methods.

### CODE REVIEW

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
1. No issue linked
2. tests files should in a tests directory. See the python suggested directory layout
3. CI seems passing but looking into the log, it is not
4. CI is not executing the tests in this PR

**Comment by nadavshoshan** [comment]
1. No issue linked- **fixed** #110 
2. tests files should in a test directory. See the python suggested directory layout-**fixed**
3. CI seems passing but looking into the log, it is not- I didn't understand the comment
4. CI is not executing the tests in this PR- @liorsicd is responsible to add it.

**Comment by liorsicd** [comment]
@lioramilbaum 
> 3. CI seems passing but looking into the log, it is not

is it the lint CI?

**Comment by lioramilbaum** [comment]
> @lioramilbaum
> 
> > 1. CI seems passing but looking into the log, it is not
> 
> is it the lint CI?

Take a look at the logs in the Checks tab. Open each step and ...boom

**Comment by liorsicd** [comment]
> > @lioramilbaum
> > > 1. CI seems passing but looking into the log, it is not
> > 
> > 
> > is it the lint CI?
> 
> Take a look at the logs in the Checks tab. Open each step and ...boom
are you meaning to this?

image

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
Are you sure the issue is linked?
Do not request to review till all issues I've mentioned are addressed

**Comment by lioramilbaum** [comment]
> > > @lioramilbaum
> > > > 1. CI seems passing but looking into the log, it is not
> > > 
> > > 
> > > is it the lint CI?
> > 
> > 
> > Take a look at the logs in the Checks tab. Open each step and ...boom
> 
> @lioramilbaum
> 
> are you meaning to this?
> 
> image

There are also errors in the 'run bootstrap.sh'

**Comment by nadavshoshan** [comment]
https://github.com/beyond-io/givit/pull/106#issuecomment-698300213
@lioramilbaum as I saw on the PR wich you approved to @rotem-benzvi.
I suggest that you will approve my PR (It will also help Rotem)
we will fix everything as mentioned in the attached comment.

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
I am becoming soft

**Comment by nadavshoshan** [comment]
Rosh Hashana spirit....

**Pull request merged**
