### PR TITLE
Our friend-feed include image items

### PR DESCRIPTION
**Pull request by rotem-benzvi**
Add images of items for first impression in the feed

fixed: #97

### CODE REVIEW

**Review by liorsicd — APPROVED** [review]

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
Please link an issue to the PR

**Comment by rotem-benzvi** [comment]
> Please link an issue to the PR

done :)

**Review by lioramilbaum — APPROVED** [review]
I didn't drill into the technical details of this PR. I am approving only because my review was addressed :-)

**Comment by rotem-benzvi** [comment]
thanks :)

**Pull request merged**
